steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
  
  # Build the app with environment variable
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'VITE_BACKEND_URL=${_BACKEND_URL}'
  
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rumi-analytica-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rumi-analytica-frontend:latest'
      - '.'
  
  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/rumi-analytica-frontend:$SHORT_SHA'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rumi-analytica-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rumi-analytica-frontend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/rumi-analytica-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/rumi-analytica-frontend:latest'

substitutions:
  _BACKEND_URL: 'http://localhost:8000'
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
