# Updated cloudbuild.yaml

steps:
  # Use the gcloud builder which includes bash, docker, and gcloud CLI
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['./build-and-deploy.sh']

# Define the images that will be created by this build
images:
  - '${_GOOGLE_CLOUD_LOCATION}-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/rumi-analytica/${_SERVICE}:latest'

# Increase the machine size to prevent timeouts during npm install or docker build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY